#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && (pylint -f json src | pylint-json2html -o index.html || true) && python -m http.server
