#!/bin/bash

TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

cd "$TOOLS_ROOT/../" && (scalene --html --profile-only "src" --outfile index.html test/test_visitor.py || true) && python -m http.server
